### ISSUE TITLE
re 2nd example simpleMPI -> simplempi

### ISSUE THREAD

**Issue by pgoddard08** [taobrienlbl/simplempi#2]
for the second example to work, `import simpleMPI`  needs to be `import simplempi`  and `smpi = simpleMPI.simpleMPI()`  needs to be `smpi = simplempi.simpleMPI()`

**Comment by taobrienlbl** [comment]
thanks @pgoddard08!

This is fixed as of v0.1.5 (no need to reinstall - it's just an update to the README.md file).  The PyPi page now shows correct code.
